services:
  nats:
    image: nats
    ports: [4222:4222]
    restart: always
    entrypoint: nats-server
    command: -js
  mongo:
    image: mongo
    ports: [27017:27017]
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    image: mongo-express
    ports: [8081:8081]
    depends_on: [mongo]
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017
  test:
    image: lukechannings/deno
    depends_on: [nats, mongo]
    volumes: [.:/code, ./.test_cache:/deno-dir]
    working_dir: /code
    entrypoint: deno
    command: test --allow-env --allow-net --no-check
    environment:
      NATS_URL: nats://nats:4222
      MONGO_URL: mongodb://root:root@mongo:27017
    profiles: [test]
